name: ideas_box_telegram_bot

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    command: [ --auth ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh mongodb:27017/test --quiet" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - 27017:27017
    volumes:
      #      - ./mongodb-data:/data/db
      - ./bot/core/db/create_user_init.js:/docker-entrypoint-initdb.d/mongo-init.js

  mongo-express:
    depends_on:
      mongo:
        condition: service_healthy
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 8081:8081

  bot:
    depends_on:
      db:
        condition: service_healthy
    build: .
    restart: always
    environment:
      - TOKEN=${TOKEN}
